[package]
name = "engine-ecs-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
bytemuck = { workspace = true }
rayon = "1.8"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }