[package]
name = "engine-ecs-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
bytemuck = { workspace = true }
rayon = "1.8"
once_cell = "1.19"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
engine-components-3d = { path = "../engine-components-3d" }
engine-camera-core = { path = "../engine-camera-core" }
engine-components-ui = { path = "../engine-components-ui" }