[package]
name = "engine-ecs-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
bytemuck = { workspace = true }
rayon = { workspace = true }
once_cell = { workspace = true }
engine-component-traits = { path = "../engine-component-traits" }

[dev-dependencies]
tokio-test = { workspace = true }
criterion = { workspace = true }