[package]
name = "engine-math-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core math functionality for Longhorn Game Engine"

[dependencies]
glam = { workspace = true }
