[package]
name = "engine-math-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
glam = { workspace = true }
serde = { workspace = true }