[package]
name = "engine-resource-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core resource functionality for Longhorn Game Engine"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
# Test dependencies if needed