[package]
name = "engine-components-2d"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "components 2d for Longhorn Game Engine"

[dependencies]
engine-component-traits = { path = "../engine-component-traits" }
serde = { workspace = true }
