[package]
name = "engine-materials-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core materials functionality for Longhorn Game Engine"

[dependencies]
# Core dependencies
glam = { workspace = true, features = ["serde"] }
serde = { workspace = true }
bitflags = { workspace = true }

# Materials shouldn't depend on renderer - renderer depends on materials

# No implementation dependencies