[package]
name = "engine-animation-import"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
engine-asset-import = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
glam = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }