[package]
name = "engine-camera-impl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "camera implementation for Longhorn Game Engine"

[dependencies]
# Core camera abstractions
engine-camera-core = { workspace = true }

# Components
engine-components-3d = { workspace = true }

# ECS
engine-ecs-core = { workspace = true }

# Math types
glam = { workspace = true }

# Serialization
serde = { workspace = true }
