[package]
name = "engine-renderer-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core renderer functionality for Longhorn Game Engine"

[dependencies]
engine-geometry-core = { workspace = true }
engine-materials-core = { workspace = true }
glam = { workspace = true }
bitflags = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
