[package]
name = "engine-texture-import"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "texture import functionality for Longhorn Game Engine"

[dependencies]
engine-asset-import = { workspace = true }
engine-resource-core = { workspace = true }

# Image processing
image = "0.24"

# Async
async-trait = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

# Compression support
tbc = "0.3"  # For BC1-7 compression

# Error handling
thiserror = { workspace = true }

# Serialization
serde = { workspace = true }
bincode = "1.3"

[dev-dependencies]
tempfile = "3.0"