[package]
name = "engine-renderer-3d"
version = "0.1.0"
edition = "2021"
description = "Standalone 3D renderer for the Longhorn Game Engine"

[dependencies]
wgpu = "0.20"
bytemuck = { version = "1.13", features = ["derive"] }
glam = "0.24"
egui = "0.28"
egui-wgpu = "0.28"
anyhow = "1.0"
log = "0.4"
pollster = "0.3"

# Internal dependencies
engine-renderer-core = { path = "../../core/engine-renderer-core" }
engine-renderer-ecs-bridge = { path = "../../integration/engine-renderer-ecs-bridge" }
engine-ecs-core = { path = "../../core/engine-ecs-core" }
engine-components-3d = { path = "../../core/engine-components-3d" }
engine-component-traits = { path = "../../core/engine-component-traits" }
engine-camera-impl = { path = "../engine-camera-impl" }
serde = { version = "1.0", features = ["derive"] }

# Example dependencies moved to engine-renderer-3d-examples crate
[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.10"