[package]
name = "engine-geometry-impl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core geometry abstractions
engine-geometry-core = { workspace = true }

# Math types
glam = { workspace = true }

# Serialization
serde = { workspace = true }