[package]
name = "engine-graphics-traits"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "graphics traits for Longhorn Game Engine"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
glam = "0.27"
thiserror = "1.0"

[dev-dependencies]
mockall = "0.11"