[package]
name = "engine-graphics-traits"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "graphics traits for Longhorn Game Engine"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
thiserror = "1.0"