[package]
name = "engine-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
engine-ecs-core = { workspace = true }
engine-renderer = { workspace = true }
engine-input = { workspace = true }
engine-assets = { workspace = true }
engine-ui = { workspace = true }
engine-platform = { workspace = true }
winit = { workspace = true }
tokio = { workspace = true }
pollster = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"