[package]
name = "engine-renderer-wgpu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
engine-renderer-core = { workspace = true }
engine-geometry-core = { workspace = true }
engine-materials-core = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
thiserror = "1.0"