[package]
name = "engine-components-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
glam = "0.24"

[dev-dependencies]
# Test dependencies if needed