[package]
name = "engine-runtime-core"
version = "0.1.0"
edition = "2021"
description = "Core runtime components for the Longhorn Game Engine"

[dependencies]
winit = "0.29"
instant = "0.1"
parking_lot = "0.12"
thiserror = "1.0"
engine-input = { workspace = true }
notify = { workspace = true }
walkdir = "2.4"
log = { workspace = true }

[dev-dependencies]
approx = "0.5"
criterion = { workspace = true }