[package]
name = "engine-graphics-wgpu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "graphics wgpu for Longhorn Game Engine"

[dependencies]
engine-graphics-traits = { path = "../../core/engine-graphics-traits" }
wgpu = "0.19"
thiserror = "1.0"

[dev-dependencies]
pollster = "0.3"