[package]
name = "engine-graphics-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
engine-graphics-traits = { path = "../../core/engine-graphics-traits" }
wgpu = "0.19"
bytemuck = { version = "1.14", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
pollster = "0.3"
winit = "0.29"