[package]
name = "engine-input"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "input for Longhorn Game Engine"

[dependencies]
engine-ecs-core = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"
