[package]
name = "structure-validator"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Validates crate structure consistency across the workspace"

[dependencies]
toml = "0.8"
toml_edit = "0.22"
anyhow = "1.0"
thiserror = "1.0"

[[bin]]
name = "validate-structure"
path = "src/main.rs"

[[bin]]
name = "migrate-structure"
path = "src/bin/migrate-structure.rs"

[dev-dependencies]
assert_fs = "1.0"