name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev
    
    - name: Generate code coverage
      run: |
        # Run tarpaulin only on core crates without GUI dependencies
        cargo tarpaulin --out Xml --timeout 300 \
          --packages engine-math-core \
          --packages engine-ecs-core \
          --packages engine-component-traits \
          --packages engine-components-3d \
          --packages engine-components-2d \
          --packages engine-geometry-core \
          --packages engine-resource-core \
          --packages engine-events-core \
          --packages engine-materials-core \
          --exclude-files "**/tests/*" \
          --exclude-files "**/examples/*" \
          --exclude-files "**/benches/*"
      env:
        RUST_BACKTRACE: 1
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cobertura.xml
        fail_ci_if_error: false
        verbose: true
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: cobertura.xml