name: Minimal Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Run tests for core crates
      run: |
        # Test individual core crates that don't require GUI dependencies
        cargo test -p engine-math-core --verbose
        cargo test -p engine-ecs-core --verbose
        cargo test -p engine-component-traits --verbose
        cargo test -p engine-events-core --verbose
    
    - name: Generate test summary
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "Core crates tested successfully" >> $GITHUB_STEP_SUMMARY