[package]
name = "engine-components-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
engine-component-traits = { path = "../engine-component-traits" }
serde = { workspace = true }