[package]
name = "engine-components-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "components ui for Longhorn Game Engine"

[dependencies]
engine-component-traits = { path = "../engine-component-traits" }
serde = { workspace = true }
