[package]
name = "engine-geometry-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Pure dependencies only - no implementation-specific crates
engine-resource-core = { path = "../engine-resource-core" }
glam = { workspace = true, features = ["serde", "bytemuck"] }
serde = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

# No graphics APIs, no external geometry libraries - pure geometric data only